### ISSUE TITLE
Чому деньги только за зомби?

### ISSUE THREAD

**Issue by m0ksem** [Shakalina/GiveMeYourMoney#1]
Хочу быть одменом на вашом напас проекте, поэтому пишу ишуе

**Comment by Shakalina** [comment]
Это можно исправить с помощью конфигурационного файла config.yml, который находиться в папке plugins\GiveMeYourMoney. Просто добавьте в секцию "mobs" название монстра и
 укажите минимальное та максимальное количество денег, которое будет с него выпадать после смерти.
![screenshot_2](https://user-images.githubusercontent.com/25805034/51974847-8448e500-2489-11e9-9323-d3c86e70d77c.png)
